version: "2"
services:
  nginx:
    build:
      context: ./dockerfile/nginx
    ports:
      - "8080:80"
    volumes:
      - ./webroot:/var/www/html
      - ./dockerfile/nginx/log:/var/log/nginx
      - ./dockerfile/nginx/conf:/etc/nginx
    depends_on:
      - php-fpm
      - mysql
  php-fpm:
    build:
      context: ./dockerfile/php
    volumes:
      - ./webroot:/var/www/html
      - ./dockerfile/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./dockerfile/php/conf/php-fpm.d.conf:/usr/local/etc/php-fpm.d/www.ini
      - ./dockerfile/php/log/fpm-php.error.log:/var/log/fpm-php.www.log
  mysql:
    build:
      context: ./dockerfile/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./dockerfile/mysql/db_data:/var/lib/mysql
